include: package:lints/recommended.yaml

analyzer:
  exclude: ['**/*.g.dart']

linter:
  rules:
    - directives_ordering
    - prefer_expression_function_bodies
    - prefer_final_locals
    - unnecessary_await_in_return
    - unnecessary_lambdas
    - cascade_invocations
    - avoid_slow_async_io
    - unnecessary_async
    - unawaited_futures
